stages:
  - build

build_dev:
  stage: build
  script:
    - npm install
    - npm pack
  environment: master

build_release:
  stage: build
  script:
    - npm install --production
    - npm shrinkwrap
    - npm pack
  environment: release